### PR TITLE
Fix E2E Intel MPI integ tests

### LINKED ISSUE #675: Failed IntelMPI E2E tests
Intel MPI E2E tests failed in CI:

https://github.com/kubeflow/mpi-operator/blob/c738a83b185b4bf3bf7e6eca9d4503653294c995/test/e2e/mpi_job_test.go#L207-L272

```shell
== BEGIN pi-launcher-jlll8 pod logs ==
 
:: initializing oneAPI environment ...
   entrypoint.sh: BASH_VERSION = 5.2.15(1)-release
   args: Using "$@" for setvars.sh arguments: mpirun -n 2 /home/mpiuser/pi
:: mpi -- latest
:: oneAPI environment initialized ::
 
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher... Retrying
Couldn't resolve pi-launcher
Resolved pi-worker-0.pi.e2e-89g8w.svc
Resolved pi-worker-1.pi.e2e-89g8w.svc
Rank 1 on host pi-worker-1
Workers: 2
Rank 0 on host pi-worker-0

== END pi-launcher-jlll8 pod logs ==
== BEGIN pi-worker-0 pod logs ==
 
:: initializing oneAPI environment ...
   entrypoint.sh: BASH_VERSION = 5.2.15(1)-release
   args: Using "$@" for setvars.sh arguments: /usr/sbin/sshd -De -f /home/mpiuser/.sshd_config
:: mpi -- latest
:: oneAPI environment initialized ::
 
Server listening on 0.0.0.0 port 2222.
Server listening on :: port 2222.
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 56026
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 36592
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 34520
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 37484
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 60796
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 35102
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 51398
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 43206
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 38376
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 46258
Accepted publickey for mpiuser from 10.244.0.26 port 36268 ssh2: ECDSA SHA256:CNZ8oQS0SYjcnyrsp2ZlAKHnT+8J+ZSTFENzWrT+9vQ
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 38498
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 37542
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 38298
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 44600
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 41802
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 52118
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 32934
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 54520
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 48770

== END pi-worker-0 pod logs ==
== BEGIN pi-worker-1 pod logs ==
 
:: initializing oneAPI environment ...
   entrypoint.sh: BASH_VERSION = 5.2.15(1)-release
   args: Using "$@" for setvars.sh arguments: /usr/sbin/sshd -De -f /home/mpiuser/.sshd_config
:: mpi -- latest
:: oneAPI environment initialized ::
 
Server listening on 0.0.0.0 port 2222.
Server listening on :: port 2222.
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 47954
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 58200
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 33168
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 42132
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 5[4286](https://github.com/kubeflow/mpi-operator/actions/runs/12369242697/job/34522856743?pr=673#step:4:4287)
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 56804
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 51658
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 56848
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 55746
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 55400
Accepted publickey for mpiuser from 10.244.0.26 port [4293](https://github.com/kubeflow/mpi-operator/actions/runs/12369242697/job/34522856743?pr=673#step:4:4294)0 ssh2: ECDSA SHA256:CNZ8oQS0SYjcnyrsp2ZlAKHnT+8J+ZSTFENzWrT+9vQ
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 37518
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 35264
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 57206
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 46430
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 40660
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 36338
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port [4307](https://github.com/kubeflow/mpi-operator/actions/runs/12369242697/job/34522856743?pr=673#step:4:4308)4
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 53162
kex_exchange_identification: Connection closed by remote host
Connection closed by 10.244.0.1 port 47790

== END pi-worker-1 pod logs ==

[...]

Summarizing 2 Failures:

[Fail] MPIJob with Intel Implementation when running as root [It] should succeed 
/home/runner/work/mpi-operator/mpi-operator/test/e2e/mpi_job_test.go:571

[Fail] MPIJob with Intel Implementation when running as non-root [It] should succeed 
/home/runner/work/mpi-operator/mpi-operator/test/e2e/mpi_job_test.go:571

Ran 13 of 13 Specs in 836.549 seconds
FAIL! -- 11 Passed | 2 Failed | 0 Pending | 0 Skipped
--- FAIL: TestE2E (836.55s)
FAIL
FAIL	github.com/kubeflow/mpi-operator/test/e2e	836.571s
FAIL
```

We have seen this problem in the following:

- https://github.com/kubeflow/mpi-operator/pull/669
- https://github.com/kubeflow/mpi-operator/pull/670
- https://github.com/kubeflow/mpi-operator/pull/671
- https://github.com/kubeflow/mpi-operator/pull/673

### PR DESCRIPTION
**Pull request by GonzaloSaez**
This should fix #675 by pinning the intel mpi packages to 2021.13 instead of the 2021.14 version that was being installed in the github actions. It is not clear to me what changed in the 2021.14 to make these tests fail but I don't think it should be a big deal. See https://github.com/GonzaloSaez/mpi-operator/actions/runs/12709381529/job/35428272102 for a build e2e run that shows the intel mpi tests passing.

### CODE REVIEW

File: build/base/entrypoint.sh [hunk 1]
```diff
@@ -26,7 +26,6 @@ function resolve_host() {
 }
 
 if [ "$K_MPI_JOB_ROLE" == "launcher" ]; then
-  resolve_host "$HOSTNAME"
```
Comment (GonzaloSaez) [inline build/base/entrypoint.sh:29]: I don't think this call is necessary, is there are reason we need to resolve the launcher hostname?

Comment (alculquicondor) [reply build/base/entrypoint.sh:29]: Yes, if the worker's can't resolve the launcher's hostname, they fail.

File: build/base/intel-builder.Dockerfile [hunk 2]
```diff
@@ -18,7 +18,7 @@ RUN apt update \
     && apt install -y --no-install-recommends \
         libstdc++-12-dev binutils procps clang \
         intel-oneapi-compiler-dpcpp-cpp \
-        intel-oneapi-mpi-devel \
+        intel-oneapi-mpi-devel-2021.13 \
```
Comment (alculquicondor) [inline build/base/intel-builder.Dockerfile:21]: I'm ok with this as a temporary solution, but eventually this version will be out of support or have CVEs, so we still need to figure what's wrong with newer versions.

WDYT @tenzen-y?

File: build/base/entrypoint.sh (hunk 1 above)
Comment (GonzaloSaez) [reply build/base/entrypoint.sh:29]: Sure but that's something that the workers should deal with not the launcher trying to resolve itself. I'll add it back in case

File: build/base/intel-builder.Dockerfile (hunk 2 above)
Comment (GonzaloSaez) [reply build/base/intel-builder.Dockerfile:21]: I did not find the exhaustive changelog for release 2021.14, but it seems they mention that they changed the default IPC exchange mechanism to be pidfd instead of drmfd which was the default. It's not clear to me if that could be the issue.

File: build/base/entrypoint.sh (hunk 1 above)
Comment (alculquicondor) [reply build/base/entrypoint.sh:29]: When I last tried, there were no retries in the Intel MPI implementation, so the pods would fail.
If the user configures `restartPolicy: Never`, then those jobs would always fail.

Waiting for the launcher to be resolvable is just more user friendly.

**Comment by alculquicondor** [comment]
Could you squash all commits please?

File: build/base/intel-builder.Dockerfile (hunk 2 above)
Comment (tenzen-y) [reply build/base/intel-builder.Dockerfile:21]: Thank you for this great investigation!
I'm ok with this solution as a short term. Could we open an issue to upgrade to 2021-.14?

Comment (tenzen-y) [reply build/base/intel-builder.Dockerfile:21]: I'm curious about the reason why we face this issue only in the github actions, though.

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve

File: build/base/intel-builder.Dockerfile (hunk 2 above)
Comment (tenzen-y) [reply build/base/intel-builder.Dockerfile:21]: https://github.com/kubeflow/mpi-operator/issues/678
